### ISSUE TITLE
NuGet Package ID already in use

### ISSUE THREAD

**Issue by ThomasPiskol** [package-url/packageurl-dotnet#12]
The package ID `PackageUrl` is already used by an unofficial package uploaded by someone else: https://www.nuget.org/packages/PackageUrl/

We can either try to get the ownership of this package ID or we change our package ID to something else.

**Comment by sschuberth** [comment]
Hmm, the "Source repository" link on the right at https://www.nuget.org/packages/PackageUrl/ links to https://raw.githubusercontent.com/package-url/packageurl-dotnet, which is this repository (although the link should actually be https://github.com/package-url/packageurl-dotnet).

So what's happening here, has the "PackageUrl" package ID been claimed meanwhile? Maybe the package owner @rasmusjelsgaard can tell?

**Comment by ThomasPiskol** [comment]
The "other" package was published in April 2020, so I expect it to contain the same source code which as present in this repo at that time. A quick check by decompiling this package shows code which is quite similar to existing source in this repo.

Nevertheless as mentioned in PR #13, I would propose to change the package ID of "our" NuGet package to `packageurl-dotnet` because:

- repository name matches the package name
- same naming convention already used for [Python](https://github.com/package-url/packageurl-python) (`packageurl-python`) and [Javascript](https://github.com/package-url/packageurl-js) (`packageurl-js`

Additionally I would propose to talk with @rasmusjelsgaard to retract the other package from nuget.org after we have published our package with the new name.

**Comment by sschuberth** [comment]
> Additionally I would propose to talk with @rasmusjelsgaard to retract the other package from nuget.org after we have published our package with the new name.

Makes sense.

**Comment by ThomasPiskol** [comment]
@sschuberth Could you review and approve my PR #13 ?
