### ISSUE TITLE
Publish release to nuget.org

### ISSUE THREAD

**Issue by rasmusjelsgaard** [package-url/packageurl-dotnet#6]
Continuing the discussion in #5, this issue is about setting up CI so releases make their onto nuget.org as official NuGet packages.
The motivation is that this will make it easy for projects that want to use this library to set it up as a dependency via package references or similar mechanism.

Suggested approach:
Find CI/CD solution that can target relevant platforms and make the tests run on all. 
On success use gitversion to figure out the relevantpackage version and publish to nuget.org.

**Comment by coderpatros** [comment]
Hey there. I was looking at the nuget package that has been published. Is that an unofficial one you've published @rasmusjelsgaard?

And a question for the maintainers. For CycloneDX we are using GitHub for CI and publishing releases, as well as pushing packages to places like nuget. It has been working pretty well. And supports running tests on Linux, MacOS and Windows.

I'd be happy to raise a PR for this repo to set that up. But wanted to check that was an acceptable choice for CI.

The approach for versioning that CycloneDX primarily uses is to have a `semver.txt` file. The basic workflow is, once a release is ready, update the version in the file, create a commit with a suitable commit message, i.e. "Bug fix release ...", and trigger the release workflow.

It works pretty well across a variety of languages/ecosystems. Which helps when switching between them as a maintainer.

I'm happy to set up as much or as little of it as you like. In terms of a nuget organisation, API key, etc. Just let me know.
