### ISSUE TITLE
Assembly does not have a strong name

### ISSUE THREAD

**Issue by dfederm** [package-url/packageurl-dotnet#8]
Without a strong name, a strong-named project will get this error.

> CS8002: Referenced assembly 'PackageUrl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

You just need to generate an snk at the root of the repo (let's say `StrongName.snk`), and add this to `Directory.Build.props`:
```xml
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)StrongName.snk</AssemblyOriginatorKeyFile>
```

**Comment by dfederm** [comment]
@ThomasPiskol Looks like you're revamping the build in #7. Are you also able to address this issue? I could submit a PR myself if desired, but I figure it might be best to have a core dev for the repo generate the key rather than some random :).

For context, I'm from a team at Microsoft working to generate SPDX for a large portion of the builds we do and are planning on taking a dependency on this library. Unfortunately our tooling needs to be strong-named which means everything we depend on needs to be strong-named. So to consume this library cleanly (ie, without strong-naming it and repackaging the library ourselves), we'll need it to be strong-named.

**Comment by dfederm** [comment]
CC @sschuberth

**Comment by ThomasPiskol** [comment]
@dfederm I would love to address this issue too, but unfortunately I'm not (yet) a contributor to this repo 🙂

**Comment by sschuberth** [comment]
> @dfederm I would love to address this issue too, but unfortunately I'm not (yet) a contributor to this repo 🙂

You don't have to be a collaborator to contribute 😉 Just create a PR from your own fork, and you'll count as a contributor (in GitHub terms) once the PR was merged.
